In [134]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = 300

In [135]:
df_incoming=pd.read_csv('SearchResults.txt',header=None)
df_incoming.head()

,0,1,2,3,4,5,6,7,8,9
0,K:\CC_DG07\DataGen\DataCheck\,OYT_TFL_20190311T1654_000001_2F9C55BD.csv,299 KB,CSV File,11/03/2019 16:54:55,11/03/2019 16:54:54,11/03/2019 16:54:54,1,748,"744,14307,744,14306,1418,14,84,2,71,1478607,66..."
1,K:\CC_DG07\DataGen\DataCheck\,OYT_TFL_20190311T1654_000004_90210435.csv,625 KB,CSV File,11/03/2019 16:54:55,11/03/2019 16:54:54,11/03/2019 16:54:54,3,929,"925,14307,4616,14306,1397,57,84,3,21,1501592,6..."
2,K:\CC_DG07\DataGen\DataCheck\,OYT_TFL_20190311T1654_000004_90210435.csv,625 KB,CSV File,11/03/2019 16:54:55,11/03/2019 16:54:54,11/03/2019 16:54:54,3,930,"926,14307,4617,14306,1408,26,84,3,21,1501592,6..."
3,K:\CC_DG07\DataGen\DataCheck\,OYT_TFL_20190311T1654_000004_90210435.csv,625 KB,CSV File,11/03/2019 16:54:55,11/03/2019 16:54:54,11/03/2019 16:54:54,3,1702,"1698,14307,5389,14306,1424,3,84,3,23,1476358,5..."
4,K:\CC_DG07\DataGen\DataCheck\,OYT_TFL_20190311T1654_000008_D8918BEB.csv,231 KB,CSV File,11/03/2019 16:54:55,11/03/2019 16:54:55,11/03/2019 16:54:55,1,194,"190,14307,26881,14306,1410,49,79,1,40,1482177,..."

In [136]:
df_data=pd.DataFrame([sub.split(",")+[df_incoming[1][i]] for i,sub in enumerate(df_incoming[9])])

In [137]:
df_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123
0,744,14307,744,14306,1418,14,84,2,71,1478607,669,,0,1154,,,Y,5389,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,732,1404,,669,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,0,,,50253,,,0,31,,12915,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000001_2F9C55BD.csv
1,925,14307,4616,14306,1397,57,84,3,21,1501592,619,,0,5389,,,Y,65511,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,619,1397,,619,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000004_90210435.csv
2,926,14307,4617,14306,1408,26,84,3,21,1501592,619,,0,5389,,,Y,65516,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,619,1407,,619,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000004_90210435.csv
3,1698,14307,5389,14306,1424,3,84,3,23,1476358,590,,0,4682,,,Y,11,,0,,,,,,,,,280,170,,,,,,,,,,,,,,,1363,,,,,0,,698,1402,,590,,,,,,,,,31,,,280,280,280,Y,,,,,,,,,,,,,,,,,,,0,,1,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000004_90210435.csv
4,190,14307,26881,14306,1410,49,79,1,40,1482177,619,,0,5389,,,Y,65517,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,,,619,,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000008_D8918BEB.csv

In [138]:
    tokenforanalysis = '5389'

In [140]:
df_token = df_data[df_data[13]==tokenforanalysis]
df_token.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123
1,925,14307,4616,14306,1397,57,84,3,21,1501592,619,,0,5389,,,Y,65511,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,619,1397,,619,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000004_90210435.csv
2,926,14307,4617,14306,1408,26,84,3,21,1501592,619,,0,5389,,,Y,65516,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,619,1407,,619,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000004_90210435.csv
4,190,14307,26881,14306,1410,49,79,1,40,1482177,619,,0,5389,,,Y,65517,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,,,619,,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1654_000008_D8918BEB.csv
2595,384,14307,7592414,14307,1010,43,79,1,40,1482177,619,,0,5389,,,Y,65520,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,,,619,,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1701_001583_6EF1FCE2.csv
2701,2020,14307,8031943,14307,1036,1,84,2,43,1474532,619,,0,5389,,,Y,65521,,0,,,,,,,,,,,,,,,,,,,,,,,,,1363,,,,,0,,619,1010,,619,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,,,,,,,,,,1,,,22431,78,12,0,31,1023,11486,65591,,,,,,,,,,,,,,,,,,,,,OYT_TFL_20190311T1702_001655_3619A723.csv

In [141]:
df_data = df_token[[13,2,17,92,123]]
df_data.columns = ["PrestigeId", "TxnSeqNo", "CardSeqNo", "CardSeqRolloverNo","FileName"]
df_data.sort_values(by=['CardSeqRolloverNo','CardSeqNo'])
df_data.to_csv("out.csv", index=False)